### ISSUE TITLE
Possible to send raw xml instead of a file location?

### ISSUE THREAD

**Issue by ebebbington** [factmaven/xml-to-json#1]
eg `https://api.domain/xml-to-json?xml=<name>ed</name>`

**Comment by ethanosullivan** [comment]
Hi Edward. This is a good idea and something to look into for sure. I'll try to investigate and see what I can do about it. Thanks.

**Comment by ebebbington** [comment]
Oh wow, good news @ethanosullivan :) I like the API, and my plan is to use this for a data format converter for Deno, is sending strings is possible, as there isn’t anything available for Deno yet and trying to write a parser from scratch is just horrible (in my experience)

**Comment by ebebbington** [comment]
I think this feature would be great actually, as I searched everywhere and I could not find one API (other than this one) to parse xml to json

**Comment by ethanosullivan** [comment]
I'm glad you like it. I made this after being in a similar position as you when I couldn't find a way to convert my dynamic XML feeds on the fly. [That made me create this API that converts APIs](https://levelup.gitconnected.com/how-to-convert-xml-to-json-without-rebuilding-your-feed-b09734329bc9).

I do agree it's a good idea especially if the XML feed isn't hosted somewhere. It should be possible to add as a new feature, but I'll need to do this in my free time. Just started a new job.

I'll keep you posted though.

**Comment by ebebbington** [comment]
No problem, I understand there’s other responsibilities! I could try take a stab it at? Of course I can run my own web server to test it, and I know PHP so I wouldn’t have any problems

**Comment by ethanosullivan** [comment]
Yeah, definitely, I was gonna actually say you can give it a shot. That would help me immensely.

I saw you made a pull request, I'll give this a test locally on my end and online and get back to you.

**Comment by ethanosullivan** [comment]
Merges and applied additional error-handling improvements. Also, updated the [readme](https://github.com/factmaven/xml-to-json/blob/master/README.md) and [changelog](https://github.com/factmaven/xml-to-json/blob/master/CHANGELOG.md).

Thanks for the assist @ebebbington. I added you to the credits for the API and readme.

**Comment by ebebbington** [comment]
Ok cool, thanks :) No problem, just happy to help out 👍
